// types.ts
export const UserAgentActionTypes = {
  GET_STATUS: "GET_STATUS",
  UPDATE_STATUS: "UPDATE_STATUS",
  API_RESPONSE_SUCCESS: "API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR: "API_RESPONSE_ERROR",
};
